### ISSUE TITLE
Problems with executeMicroflowAsUser_1 in Mx6

### ISSUE THREAD

**Issue by RCatersels** [mendix/CommunityCommons#19]
Roeland,

No matter what I do the Java action throws a nullpointer if this microflow is triggered by a scheduled event in Mx 6.9.1. If I trigger the microflow manually the microflow just works and the microflow is run as the user that I gave in the parameter. Are there still some problems with user context in Mx6 that you know off?
We need this Java action in a scheduled event because of the translation of database content. 

Regards,

Ronald

**Comment by davelina** [comment]
I want to raise this issue, because I just can't get the executeAsUser (or the _1 or the _2 version) to work. 
I get the following error message, but you can't do much with it: 
`com.mendix.modules.microflowengine.MicroflowException: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: java.lang.NullPointerException
	at Basis._0_ScheduledEventsStartFlow_Wintertijd.nested.b7ef1bfa-5117-415f-825e-bf7267e95491 [0 of 1] (JavaAction : 'executeMicroflowAsUser_1')
	at Basis._0_ScheduledEventsStartFlow_Wintertijd (NestedLoopedMicroflow : '')`

Hopefully, you can help us out! If you need anything, give us a reply. 

Regards, 
Dave

**Comment by RoelandSalij** [comment]
Hi Dave, I talked to Ronald on the meetup yesterday and he told me you found a fork on GitHub which fixes the issue. Can you point me to the fix so I know what should be merged?

**Comment by davelina** [comment]
Hi Roeland, 

I used the fork for mx7 created by dllhartveld:
https://github.com/mendix/CommunityCommons/compare/master...dlhartveld:mx7

I think most of the changes are in the Core.java not necessarily in the executeMicroflowAsUser java actions. 

Hope this helps

**Comment by RoelandSalij** [comment]
@dlhartveld Would you please create a pull request? :)

**Comment by dlhartveld** [comment]
Ok, so that repo fork is in my account and not under @mendix for a reason ;-)

I was experimenting with the connector kit features like using a Microflow type instead of a string for the microflow to execute as a different user, to see how the API of this library could be improved. Please be careful with this fork, because it is **experimental and untested**!

If @davelina's previous comment is correct, however, then the fix should be to just run on Mendix 6.9.1 - I don't believe I committed anything other than the changes to the java actions by a conversion to Mendix 6.9.1.

**Comment by ako** [comment]
David has a point here, official changes to this module should be handled by the runtime team.
If someone wants to try out david's suggestions, they can fork david's repo and create their own version.
Ofcourse, a pull request is always welcome for things considered ready for official master.

**Comment by RCatersels** [comment]
We need the commit of Bart Luijten: https://github.com/dlhartveld/CommunityCommons/commit/a4fce0a66e59d8dd3fa9b08f3909e80f1d4c34d0
Bart identified the bug only he did the commit in fork of David for some unknown reason. His commit fixes this bug.

**Comment by RCatersels** [comment]
And the problem is no longer for ourselves because we adjusted the Java code. But in my opinion everybody on Mx6 that uses this Java action in a scheduled event will encounter this bug.

**Comment by dlhartveld** [comment]
The same commit exists in this repository on master: a4fce0a66e59d8dd3fa9b08f3909e80f1d4c34d0

But the App Store version of the module is from an earlier commit. Hence the issue still exists when the official version is used.

**Comment by RoelandSalij** [comment]
Commit is in release of version 6.0
